apiVersion: v1
kind: Service
metadata:
  name: fe-svc
  labels:
    name: kubestriker
    app: kubestriker
    component: frontend-server
spec:
  type: LoadBalancer
  selector:
    app: kubestriker
    component: frontend-server
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
      name: ks-fe-svc
