apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubestriker-fe
  namespace: kubestriker
  labels:
    app: kubestriker
    release: kubestriker
    component: frontend-server
spec:
  # serviceName: "kubestriker-python-svc"
  replicas: 1
  selector:
    matchLabels:
      app: kubestriker
      release: kubestriker
      component: frontend-server
  template:
    metadata:
      labels:
        app: kubestriker
        release: kubestriker
        component: frontend-server
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: kubestriker
                  release: "kubestriker"
                  component: frontend-server
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 60
      # serviceAccountName: consul-dev-frontend-server
      volumes:
        - name: kubestriker-python-storage
          emptyDir: {}
      containers:
        - name: kubestriker-python
          image: "cloudsecguy/kubestrikerfe:env6"
          env:
            - name: ADVERTISE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: API_URL
              value: "http://192.168.18.107:8888/"
          volumeMounts:
            - name: kubestriker-python-storage
              mountPath: /data
              subPath: data
          ports:
            - name: kubestriker-fe
              containerPort: 80
              protocol: "TCP"
            - name: python-server
              containerPort: 8888
              protocol: "TCP"
          # livenessProbe:
          #   tcpSocket:
          #     port: 8000
          #   failureThreshold: 2
          #   initialDelaySeconds: 5
          #   periodSeconds: 3
          #   successThreshold: 1
          #   timeoutSeconds: 2
          # readinessProbe:
          #   tcpSocket:
          #     port: 8000
          #   failureThreshold: 2
          #   initialDelaySeconds: 5
          #   periodSeconds: 3
          #   successThreshold: 1
          #   timeoutSeconds: 5
