apiVersion: v1
kind: ConfigMap
metadata:
  name: kubestriker-neo4j-common-config
data:
  NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
  NUMBER_OF_CORES: "3"
  AUTH_ENABLED: "true"
  # Enable listening for backups; default port 6362
  NEO4J_dbms_backup_enabled: "true"
  NEO4J_dbms_default__database: "neo4j"
  NEO4J_dbms_connector_bolt_listen__address: 0.0.0.0:7687
  NEO4J_dbms_connector_http_listen__address: 0.0.0.0:7474
  NEO4J_dbms_connector_https_listen__address: 0.0.0.0:7473
  NEO4J_dbms_jvm_additional: "-XX:+ExitOnOutOfMemoryError"
  NEO4JLABS_PLUGINS: "[\"apoc\"]"
  NEO4J_apoc_import_file_use__neo4j__config: "true"