# Source: neo4j/templates/discovery-lb.yaml
apiVersion: v1
kind: Service
metadata:
  name: discovery-tester-neo4j-0
  labels:
    neo4j.com/coreindex: "0"
    neo4j.com/cluster: tester-neo4j
    neo4j.com/role: CORE
    neo4j.com/bolt: "false"
    neo4j.com/http: "false"
    app.kubernetes.io/instance: "tester"
    app.kubernetes.io/name: neo4j
    app.kubernetes.io/component: core
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-discovery
      port: 5000
      targetPort: 5000
      protocol: TCP
    - name: tcp-transaction
      port: 6000
      targetPort: 6000
      protocol: TCP
    - name: tcp-raft
      port: 7000
      targetPort: 7000
      protocol: TCP
    - name: tcp-jmx
      port: 3637
      targetPort: 3637
      protocol: TCP