apiVersion: v1
kind: Service
metadata:
  name: neo4j-fe
  labels:
    name: kubestriker
    app: kubestriker
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: kubestriker
    component: frontend
  ports:
    - port: 4000
      protocol: TCP
      targetPort: 4000
      name: neo4j-fe