apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j-fe
  namespace: kubestriker
  labels:
    app: kubestriker
    release: kubestriker
    component: frontend
spec:
  serviceName: "neo4j-fe"
  replicas: 1
  selector:
    matchLabels:
      app: kubestriker
      release: kubestriker
      component: frontend
      hasDNS: "true"
  template:
    metadata:
      labels:
        app: kubestriker
        release: kubestriker
        component: frontend
        hasDNS: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: kubestriker
                  release: "kubestriker"
                  component: frontend
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 60
      volumes:
        - name: neo4j-storage
          emptyDir: {}
      containers:
        - name: neo4j-fe
          image: "cloudsecguy/neo4jchai:chaipub"
          env:
            - name: ADVERTISE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: neo4j-storage
              mountPath: /data
              subPath: data
          ports:
            - name: neo4j-fe-svc
              containerPort: 4000
              protocol: "TCP"
          # livenessProbe:
          #   tcpSocket:
          #     port: 8000
          #   failureThreshold: 2
          #   initialDelaySeconds: 5
          #   periodSeconds: 3
          #   successThreshold: 1
          #   timeoutSeconds: 2
          # readinessProbe:
          #   tcpSocket:
          #     port: 8000
          #   failureThreshold: 2
          #   initialDelaySeconds: 5
          #   periodSeconds: 3
          #   successThreshold: 1
          #   timeoutSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            runAsGroup: 1000
            runAsUser: 1000