apiVersion: v1
kind: Service
metadata:
  name: python-svc
  labels:
    name: kubestriker
    app: kubestriker
    component: server
spec:
  type: ClusterIP
  selector:
    app: kubestriker
    component: server
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: python-svc