apiVersion: v1
kind: Service
metadata:
  name: python-svc
  labels:
    name: kubestriker
    app: kubestriker
    component: server
spec:
  type: LoadBalancer
  selector:
    app: kubestriker
    component: server
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
      name: python-svc