apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubestriker-db
  namespace: kubestriker
  labels:
    app: kubestriker
    release: kubestriker
    component: database
spec:
  # serviceName: "kubestriker-db-svc"
  replicas: 1
  selector:
    matchLabels:
      app: kubestriker
      release: kubestriker
      component: database
      hasDNS: "true"
  template:
    metadata:
      labels:
        app: kubestriker
        release: kubestriker
        component: database
        hasDNS: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: kubestriker
                  release: "kubestriker"
                  component: database
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 60
      # serviceAccountName: consul-dev-server
      volumes:
        - name: kubestriker-db-storage
          emptyDir: {}
      containers:
        - name: kubestriker-db
          image: "amazon/dynamodb-local:latest"
          env:
            - name: ADVERTISE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DYNAMODB_ACCESS_KEY_ID
              value: "anything"
            - name: DYNAMODB_ACCESS_KEY
              value: "anything"
            - name: DYNAMODB_REGION
              value: "ap-southeast-2"
          volumeMounts:
            - name: kubestriker-db-storage
              mountPath: /data
              subPath: data
          ports:
            - name: db-service
              containerPort: 8000
              protocol: "TCP"
          # livenessProbe:
          #   tcpSocket:
          #     port: 8000
          #   failureThreshold: 2
          #   initialDelaySeconds: 5
          #   periodSeconds: 3
          #   successThreshold: 1
          #   timeoutSeconds: 2
          # readinessProbe:
          #   tcpSocket:
          #     port: 8000
          #   failureThreshold: 2
          #   initialDelaySeconds: 5
          #   periodSeconds: 3
          #   successThreshold: 1
          #   timeoutSeconds: 5
          # securityContext:
          #   allowPrivilegeEscalation: false
          #   privileged: false
          #   runAsGroup: 1000
          #   runAsUser: 1000
          #   capabilities:
          #     drop:
          #       - ALL
          #     add:
          #       - NET_BIND_SERVICE
          #       - SYS_TIME
          # resources:
          #   limits:
          #     cpu: 100m
          #     memory: 100Mi
          #   requests:
          #     cpu: 100m
          #     memory: 100Mi